### ISSUE TITLE
Draft goals

### ISSUE THREAD

**Issue by todaywasawesome** [argoproj/argo-conformance-program#3]
Document the goals of the conformance program and start gathering important ideas that will need to be part of the standard. 

Inspiration:

- Prometheus https://github.com/cncf/prometheus-conformance 
- Kubernetes https://www.cncf.io/certification/software-conformance/ 
- Crossplane https://github.com/cncf/crossplane-conformance 
- https://github.com/argoproj/argo-conformance-program/blob/main/README.md

**Comment by todaywasawesome** [comment]
Notes from committee meeting 9/16. The decision was made to move forward in creating the standard. 

Do we think a conformance program is merited? 

- [x] Do we think a conformance program is merited
- [Henrik] conformance done right will help, done wrong will harm
- [Hong] Don’t want to feel rushed on this
- Is there an impact on graduation, this may be too much and a mixed-signal
- Argo brand wasn’t built in a month, it took 4 years.
- User experience is very important and unique
- (Jann) The value to Kubernetes for conformance is you know your manifests will run, the API is clear and works. Is this a use case that exists for Argo?
- [Hong] GitOps engine is more straightforward for certification, Argo is more than just the API
- [Dan] Anyone can take and fork Argo, the name is a carrot we can use to ensure interoperability
- [Hong] if anyone forks it could bring bad impressions onto the project
- [Jann] Amazon or Google could offer Workflows but call it their own thing. Conformance can drive additional resources into the project. We’ve seen this in Codefresh and Redhat. 
- [Hong] Argo brand is more important than our brand, someone could take Argo and meet conformance but not contribute back
- [Henrik] Intuit wants Argo to be strong and to grow the community, this is why we OSS in the beginning. We want to make sure the brand is maintained and the distributions that come out are Argo. I’d like some requirements to maintain some level of contribution to the project, something like 2 members on the project
- [Hong] How expensive to maintain conformance? 
- [Henrik] usually conformance is tied to a version or a year. The CNCF provides legal resources to take action when people fall out of compliance. Trademark is one of the biggest things they have
- [Hong] need to make sure we’re clear on the value, and enforcement. Jesse and I are more conservative on this. Ok to work on the proposal, want to make sure it’s strong enough to actually present. It can’t be thrown together. If we put something up that’s not beneficial it could drive people away.
- [Hong] I’m more concerned about the use of the name, Prometheus is a certification more so than permission to use the name. 
- [x] What are the sacred cows
- Key goal: Good for the community
- CNCF Member
- API Compatability
- User Interface consistency ****
- Potentially underlying code consistency, is there a way to enforce this? What do we get and give up?
- Contributions to the community

**Comment by edlee2121** [comment]
Conformant products are required to be up-to-date with latest stable argo releases.
